java/src/main/java/org/mifos/community/ai/mcp/MifosX.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
Introduced a new method `getAllClients` in both `MifosX` and `MifosXClient` classes. This allows retrieving a list of all clients from the Fineract API for enhanced data access.
=> Add functionality to retrieve all clients

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/Address.java, java/src/main/java/org/mifos/community/ai/mcp/dto/FamilyMember.java
Introduced `FamilyMember` and `Address` DTOs to standardize data handling. Added endpoints and methods to create and manage family members under a client. This update enhances the system's capability to handle client-related familial and address information efficiently.
=> Add support for managing family members and addresses

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Added default values for middleName, qualification, isDependent, and professionId to ensure proper handling of null inputs. This prevents potential null pointer issues and ensures consistent data integrity.
=> Handle null values for family member attributes

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Updated descriptions for tool arguments to use user-friendly examples. Refactored profession handling to map string inputs to predefined IDs, improving code readability and flexibility. Default values and error handling remain unchanged.
=> Refactor tool arguments and profession handling logic

python/app.py
Added remaining features of current mcp implementation in python from node
=> Update app.py with remaining features 

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Revised hardcoded IDs to match updated configuration standards. This ensures data consistency and aligns with the latest system requirements.
=> Update ID mappings for address, profession, and gender

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/Codes.java, java/src/main/java/org/mifos/community/ai/mcp/dto/FamilyMember.java
Added `Codes` DTO and updated `FamilyMember` with default IDs and Jackson annotations. Simplified code value retrieval in `MifosXServer` using dynamic API calls, removing hardcoded logic for professions, genders, and marital statuses. Introduced new endpoints for fetching codes and code values in `MifosXClient`.
=> Refactor FamilyMember logic and enhance code handling

java/pom.xml, java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/dto/Address.java, java/src/main/java/org/mifos/community/ai/mcp/dto/FamilyMember.java
Added Jakarta Bean Validation for `Address` and updated `MifosXServer` to handle validation exceptions. Modified `FamilyMember` and `Address` default and code value IDs. Adjusted request parameter handling and descriptions for clarity and consistency.
=> Update validation, IDs, and request handling in MCP DTOs

mcp_experimentation_in_python/github_assistant_mcp.py
Can be used all across mifos repos for various tasks ranging from analysis, pr, and other user info. was made using agno and mcp
=> new mcp implementation added with agno for github

mcp_experimentation_in_python/mcp_agent.config.yaml, mcp_experimentation_in_python/requirements.txt, mcp_experimentation_in_python/slack_based_bot.py
Can be easily used for official MIFOS slack where wide range of tasks can be done using this slack assistant
=> mcp_based slack bot with local file system access

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Corrected the description wording to clarify the activation process. This ensures better readability and accuracy for users of the method.
=> Update tool description for client activation method

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
Updated `activateClient` to use `@PathParam` and `@QueryParam` annotations for better API structure and clarity. Adjusted method call to include 'activate' as a query parameter.
=> Refactor client activation API method signature.

java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
Updated the addAddress method to replace inline query parameters with `@PathParam` and `@QueryParam` annotations. This improves code clarity and adheres to best practices for RESTful API interaction.
=> Refactor addAddress method to use proper annotations

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
Introduced a logger to MifosXServer and added an info log to output the formatted JSON address before sending it to the client. This improves traceability and debugging by logging critical data transformation steps.
=> Add logging for JSON address in MifosXServer

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Added validation logic for SavingProduct and refactored currency code retrieval to a new helper method. Improved method reliability with injected ObjectMapper and Validator. Introduced foundation for saving account applications using JsonNode.
=> Refactor and enhance SavingProduct setup with validation

java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/Currency.java, java/src/main/java/org/mifos/community/ai/mcp/dto/CurrencyResponse.java
Introduced a new API endpoint in `MifosXClient` to retrieve currency data. Added `Currency` and `CurrencyResponse` DTO classes to structure the fetched currency details, including code, name, and display attributes.
=> Add support for fetching available currencies

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/SavingProductApplication.java
Introduced `SavingProductApplication` DTO and extended `MifosXClient` with endpoints for creating and retrieving savings account templates. Enhanced `MifosXServer` tool to handle saving account applications, integrating template-driven data initialization and JSON serialization.
=> Add support for saving account applications via Mifos system

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Corrected the condition to check `externalId` instead of `mobileNo` and fixed the method call to properly handle saving account applications. These changes ensure better logic consistency and prevent potential misbehavior in field assignments and API calls.
=> Fix incorrect field checks and method usage in MCP server.

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/SavingAccountActivation.java
Introduced a new API endpoint for approving savings accounts by account number. Created a `SavingAccountActivation` DTO to encapsulate activation details like date, format, locale, and approval note. Updated relevant methods and classes to integrate with the new functionality.
=> Add support for savings account approval

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Added a more descriptive annotation to `approveSavingsAccount` method, providing clarity on its purpose and usage. This improves code readability and assists developers in understanding the method's functionality.
=> Update tool annotation for savings account approval method

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/dto/SavingAccountApproval.java
Renamed variables and methods to better reflect their purpose and updated corresponding DTOs. Introduced `SavingAccountApproval` DTO to separate approval logic from activation, improving code organization. Made the "note" parameter optional in approval while removing it from activation for simplicity.
=> Refactor savings account operations for clarity and consistency.

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/PaymentType.java, java/src/main/java/org/mifos/community/ai/mcp/dto/SavingsTransaction.java, java/src/main/java/org/mifos/community/ai/mcp/dto/SavingsTransactionTemplate.java
Introduced functionality to create savings transactions, including deposits and withdrawals, with validations for input data. Added DTOs for SavingsTransaction, PaymentType, and SavingsTransactionTemplate, along with corresponding API methods in MifosXClient and their integration in MifosXServer. This update enables handling savings transactions with customizable options like payment type, transaction date, and notes.
=> Add savings transaction support for clients

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Replaced references to client ID with account number in the method handling new savings transactions. Updated parameter descriptions and method implementation to reflect this change, ensuring consistency and accuracy in transaction processing.
=> Update savings transaction parameter from client ID to account number

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/dto/DateArrayDeserializer.java, java/src/main/java/org/mifos/community/ai/mcp/dto/SavingsTransactionTemplate.java
Refactored transaction date handling in SavingsTransactionTemplate by replacing the hardcoded current date with the actual date provided in the JSON payload for consistency.
Introduced DateArrayDeserializer to support deserialization of date arrays formatted as [year, month, day], converting them into human-readable strings or LocalDate objects as needed. This ensures proper parsing of date and submittedOnDate fields from JSON and facilitates seamless integration with Java date handling.
=>  Improve transaction date handling with custom deserialization

java/src/main/java/org/mifos/community/ai/mcp/dto/PaymentType.java
Added the `codeName` field to the `PaymentType` class to support additional metadata. This change ensures better extensibility and allows for more descriptive identifiers in payment processing.
=> Add codeName attribute to PaymentType DTO

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
Added allowAttributeOverrides property to the default loan product creation JSON
=> Fix in default loan product creation

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/LoanAccountApproval.java, java/src/main/java/org/mifos/community/ai/mcp/dto/LoanAccountApprovalTemplate.java
Introduced methods to approve and activate loan accounts with required parameters and validations. Updated DTOs to handle loan approval templates, maintaining flexibility for optional fields such as approval date and notes.
=> Add loan account approval support

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java, java/src/main/java/org/mifos/community/ai/mcp/dto/DisburseLoanAccount.java, java/src/main/java/org/mifos/community/ai/mcp/dto/DisburseLoanAccountTemplate.java, java/src/main/java/org/mifos/community/ai/mcp/dto/LoanRepaymentInstallment.java, java/src/main/java/org/mifos/community/ai/mcp/dto/LoanTransactionType.java
Introduced new DTOs for loan disbursement, loan transactions, and repayment installments. Updated `MifosXClient` and `MifosXServer` to include APIs for loan disbursement functionality, supporting payment details and transaction validation. Removed redundant logging for cleaner code.
=> Add loan disbursement functionality and related DTOs

java/backoffice/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/backoffice/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
- Improve search tool to use externalId consistently
- Update approveSavingsAccount tool
- Update activateSavingsAccount tool
- Enable tools to work with externalId as input
=> Savings accounts support

java/backoffice/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java, java/backoffice/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
- Fixed grammar and spelling in @Tool and @ToolArg descriptions
- Standardized terminology
- Clarified optional vs required fields in descriptions
- Improved readability for AI agent understanding
=> Enhance tool descriptions and argument details for better clarity
