java/src/main/resources/application.properties

Introduced a new method `listClients` in both `MifosXServer` and `MifosXClient` classes. This allows retrieving a list of all clients from the Fineract API for enhanced data access.

Add functionality to retrieve all clients

---

java/src/main/resources/application.properties

Updated the application.properties file to set the default MIFOSX_BASE_URL to the production API endpoint. The sandbox URL was commented out to reflect the change in focus towards the production environment. This ensures proper configuration for live deployments.

Set default MIFOSX_BASE_URL to production environment

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java

Corrected the annotation syntax for the 'qualification' parameter by moving 'required = false' outside the description text. This ensures proper parsing and functionality of the annotation

Fix typo in ToolArg annotation for 'qualification' parameter

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java

Previously, the addFamilyMember method directly passed a FamilyMember object. This update changes it to serialize the object into a JSON string before sending it to the MifosXClient, ensuring proper handling of non-null fields via Jackson's JsonInclude settings.

Refactor addFamilyMember to serialize FamilyMember as JSON

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/dto/FamilyMember.java

Replaced `relationshipId` with `relationship` and updated references accordingly. Introduced logic to map human-readable relationship strings (e.g., "father", "mother") to corresponding IDs for consistency. Default value fallback ensures robustness.

Update relationship field and add string-based mapping logic

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java

Updated gender and marital status arguments to accept strings and added mappings for their respective IDs. Removed hardcoded defaults and replaced them with switch-case logic for dynamic handling based on input values.

Refactor gender and marital status handling in MifosXServer

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java

Added a missing break statement in the gender switch to prevent fall-through behavior. This ensures proper execution flow and eliminates any unintended logic errors.

Fix missing break statement in gender switch

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/dto/FamilyMember.java

Renamed the 'relationship' field to 'relationshipId' in the FamilyMember DTO and updated references accordingly in MifosXServer. This improves naming consistency and clarity within the codebase.

Refactor relationship field to relationshipId in FamilyMember

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java

Update @ToolArg descriptions to specify replacement with empty strings when values are not provided, improving clarity. Refactor the profession switch to remove unnecessary braces for better code readability.

`Clarify @ToolArg descriptions and refactor profession switch`

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
java/src/main/java/org/mifos/community/ai/mcp/dto/Address.java

Introduced functionality to add addresses to clients, including enhancements in `MifosXClient` and `MifosXServer`. Refactored `Address` DTO to update `stateProvinceId` type and consolidated imports for better readability. Adjusted default IDs for profession, gender, and marital status mappings.

Add support for client address management in MifosX

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java

Revised the description for the `isDependent` parameter to reflect accurate expected input. Added a default `relationshipId` value of 25 to ensure consistent data handling.

Update `isDependent` description and set default relationship ID

---

java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java

The @PathParam annotation for clientId was removed to simplify method parameters and better align with API design. This change ensures consistency in the parameter handling for the addAddress method.

Remove @PathParam annotation from addAddress method

---

java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java

Simplified the @Path annotation for the addAddress method by moving the addressTypeId parameter directly into the URL path. This change improves readability and aligns with standard RESTful API conventions.

Refactor URL path for addAddress API method

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
java/src/main/java/org/mifos/community/ai/mcp/dto/ClientActivation.java

Introduce functionality to activate a client account via API, including the ability to specify an activation date or default to the current date. Added `ClientActivation` DTO for handling activation details and updated `MifosXClient` and `MifosXServer` to process activation requests.

Add client activation API support

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/dto/Address.java

Replaced `addressTypeId` with `addressType` in both `Address` DTO and `MifosXServer` client method call to ensure proper mapping. Added `@NotNull` annotation to enforce validation for `addressType`. This change ensures consistency and improves data handling.

Refactor Address DTO and fix method parameter usage.

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java

Replaced `setAddressTypeId` with `setAddressType` to correctly map and assign the address type. This ensures that the address initialization logic aligns with the expected method usage and prevents potential misconfigurations.

Fix incorrect method call for setting address type

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/dto/Address.java

Updated the address-related parameter names and mappings to align with new naming conventions. Added a placeholder method `createDefaultSavingProduct` for future implementation. Improved clarity and maintainability of the code.

Refactor address field mappings in MifosXServer

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
java/src/main/java/org/mifos/community/ai/mcp/dto/Charge.java
java/src/main/java/org/mifos/community/ai/mcp/dto/SavingProduct.java

Introduced `SavingProduct` and `Charge` DTOs to define the structure and validation for default savings products. 
Added a new API endpoint in `MifosXClient` to support streamlined product creation. 
Updated `createDefaultSavingProduct` in `MifosXServer` to use this endpoint and apply default configurations, requiring minimal input from users. This improves maintainability and enhances the overall savings product management workflow.

Add support for default savings product creation with DTOs and API integration

---

java/src/main/java/org/mifos/community/ai/mcp/dto/LoanProductApplication.java

Corrected the class name from LoanProdctApplications to LoanProductApplication to fix a typo and align with naming conventions. This ensures clarity and consistency across the codebase.

Rename class to LoanProductApplication

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java

Introduced a new endpoint to activate savings accounts using their account number. The implementation includes optional parameters for notes and activation dates, ensuring flexibility and improved usability for account activation workflows.

Add support for activating savings accounts via API

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java
java/src/main/java/org/mifos/community/ai/mcp/client/MifosXClient.java
java/src/main/java/org/mifos/community/ai/mcp/dto/AllowAttributeOverrides.java
java/src/main/java/org/mifos/community/ai/mcp/dto/LoanProduct.java
java/src/main/java/org/mifos/community/ai/mcp/dto/Options.java

Added support for quick creation of standard loan products. Only key parameters such as name, principal amount, frequency, and nominal interest rate are required, while default values are automatically set for all other fields. Included necessary classes to handle generated JSON structures and their corresponding data types.

Support for default loan product creation

---

java/src/main/java/org/mifos/community/ai/mcp/MifosXServer.java

This change adds a single log statement to print the full JSON structure of the loanProduct object before it is sent to the backend. No other logic was modified.

Added logging to inspect loanProduct payload before backend submission

---

java/src/main/java/org/mifos/community/ai/mcp/dto/Currency.java

Added the inMultiplesOf field and @JsonInclude(Include.NON_NULL) to the Currency class to exclude null fields from serialization. This results in cleaner JSON output and improves API response clarity.

Fix DisburseLoanAccountTemplate:
